在小量的資料上，我們用眼睛就可以看得出來程式碼是否有跑出我們理想中的結果

請嘗試想像一個你需要的資料結構 (裡面的值可以是隨機的)，然後用上述的方法把它變成 pandas DataFrame

Ex: 想像一個 dataframe 有兩個欄位，一個是國家，一個是人口，求人口數最多的國家
Hints: 隨機產生數值

In [1]:
import numpy as np
np.random.rand(10)

array([0.13842843, 0.87766809, 0.21253496, 0.64323476, 0.94719608,
       0.93984825, 0.9891422 , 0.59565779, 0.53825663, 0.50107192])

In [2]:
# normal distribution
np.random.randn(10)

array([ 1.04327892,  0.55936702, -1.03247947,  0.3374647 , -0.3994103 ,
        0.24142953, -0.76899402, -1.73740193, -0.30406699,  0.92462629])

In [3]:
np.random.randint(10, size = 10)

array([8, 3, 4, 5, 3, 7, 8, 3, 1, 3])

In [5]:
import pandas as pd
import numpy as np

In [17]:
data = {
    'country': ['Taiwan','Japan','USA','Iceland','England'],
    'city': ['Taipei', ' Tokyo', 'Washington','Reykjavik', 'London'],
    'weekday': ['Sun', 'Sun', 'Sun', 'Mon', 'Mon'],
    'visitors': np.random.randint(1000000,size = 5)
}

visitors_1 = pd.DataFrame(data)

visitors_1

country        city weekday  visitors
0   Taiwan      Taipei     Sun    972985
1    Japan       Tokyo     Sun    314377
2      USA  Washington     Sun    322273
3  Iceland   Reykjavik     Mon    143581
4  England      London     Mon     25921

In [18]:
visitors_1.groupby(by = 'weekday')['visitors'].mean()

weekday
Mon     84751
Sun    536545
Name: visitors, dtype: int64